spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nsuffer
    username: nsuffer
    password: nsuffer


notion:
  database: c1b4b8a152e94d90909717d92be2c116
  token: secret_LSshj9zJf38xrnerHSLW0fZLLxYmFtPkx1nNCeqEAUX